### ISSUE TITLE
ProcessError / LOCKERROR with Conda

### ISSUE THREAD

**Issue by cdeil** [spacetelescope/asv#192]
I tried the explicit `"environment_type" : "conda"` for the first time and after a while it ran into this error:
```bash
ChristophMacbook-2:gammapy-benchmarks deil$ asv run v0.1..master --steps 1
· Fetching recent changes..
· Creating environments
·· Creating conda environment for py2.7-astropy-numpy-scipy.
·· Error running /Users/deil/software/anaconda/anaconda3/bin/conda create --yes -p env/e7691aba7f7218b7a5c86351fe4bd1f8 --use-index-cache python=2.7 pip
             STDOUT -------->
             Fetching package metadata: ...
             Solving package specifications: 
             STDERR -------->
             
 
·· Failure creating conda environment for py2.7-astropy-numpy-scipyTraceback (most recent call last):
  File "/Users/deil/Library/Python/3.4/bin/asv", line 9, in <module>
    load_entry_point('asv==0.1', 'console_scripts', 'asv')()
  File "/Users/deil/code/asv/asv/main.py", line 36, in main
    result = args.func(args)
  File "/Users/deil/code/asv/asv/commands/__init__.py", line 45, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/Users/deil/code/asv/asv/commands/run.py", line 130, in run_from_conf_args
    dry_run=args.dry_run, machine=args.machine
  File "/Users/deil/code/asv/asv/commands/run.py", line 188, in run
    environments = Setup.run(conf=conf, parallel=parallel)
  File "/Users/deil/code/asv/asv/commands/setup.py", line 67, in run
    env.setup()
  File "/Users/deil/code/asv/asv/plugins/conda.py", line 108, in setup
    'pip'])
  File "/Users/deil/code/asv/asv/util.py", line 219, in check_call
    dots=dots, display_error=display_error, shell=shell, env=env)
  File "/Users/deil/code/asv/asv/util.py", line 330, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/Users/deil/software/anaconda/anaconda3/bin/conda create --yes -p env/e7691aba7f7218b7a5c86351fe4bd1f8 --use-index-cache python=2.7 pip' returned non-zero exit status -15
ChristophMacbook-2:gammapy-benchmarks deil$ /Users/deil/software/anaconda/anaconda3/bin/conda create --yes -p env/e7691aba7f7218b7a5c86351fe4bd1f8 --use-index-cache python=2.7 pip
Fetching package metadata: ...
Solving package specifications: .
Package plan for installation in environment /Users/deil/code/gammapy-benchmarks/env/e7691aba7f7218b7a5c86351fe4bd1f8:
 
The following NEW packages will be INSTALLED:
 
    openssl:    1.0.1j-5     
    pip:        6.0.6-py27_0 
    python:     2.7.9-1      
    readline:   6.2-2        
    setuptools: 11.3.1-py27_0
    sqlite:     3.8.4.1-0    
    tk:         8.5.15-0     
    zlib:       1.2.8-0      
 
Linking packages ...
    LOCKERROR: It looks like conda is already doing something.                                                                                          |  12%
    The lock /Users/deil/software/anaconda/anaconda3/pkgs/.conda_lock-64011 was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 1 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock /Users/deil/software/anaconda/anaconda3/pkgs/.conda_lock-64011 was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 2 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock /Users/deil/software/anaconda/anaconda3/pkgs/.conda_lock-64011 was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 4 seconds
^CTraceback (most recent call last):
  File "/Users/deil/software/anaconda/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/deil/software/anaconda/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/Users/deil/software/anaconda/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/Users/deil/software/anaconda/anaconda3/lib/python3.4/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/Users/deil/software/anaconda/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 397, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/deil/software/anaconda/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 587, in execute_actions
    execute_plan(plan, index, verbose)
  File "/Users/deil/software/anaconda/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 569, in execute_plan
    link(prefix, arg, index=index)
  File "/Users/deil/software/anaconda/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 525, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/deil/software/anaconda/anaconda3/lib/python3.4/site-packages/conda/install.py", line 503, in link
    with Locked(prefix), Locked(pkgs_dir):
  File "/Users/deil/software/anaconda/anaconda3/lib/python3.4/site-packages/conda/lock.py", line 57, in __enter__
    sleep(sleeptime)
KeyboardInterrupt
```

**Comment by cdeil** [comment]
`conda clean --lock` resolved the issue:
https://gist.github.com/cdeil/55c895fb786c51df2fc4

Is there anything `asv` to drive `conda` differently to avoid this issue?
If no, just close this issue ... I can't seem to reproduce it ...

**Comment by mdboom** [comment]
It looks like the lock was created by something before `asv` even started.  So I don't think there's much we can do on our end.  I certainly wouldn't want to forcefully clear the lock: I'm sure it exists for a reason.
