### ISSUE TITLE
New setuptools breaks scipy install

### ISSUE THREAD

**Issue by pv** [spacetelescope/asv#207]
The setuptools version 12.0.5 currently (on Feb 2015) installed by a8ffa6b9c6b does this:
```
/mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/bin/pip install /mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/project
Unpacking ./env/b35678fc20e92d459a63ed5094f8dbc9/project
  Running setup.py (path:/tmp/pip-juyNdo-build/setup.py) egg_info for package from file:///mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/project
    /mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/local/lib/python2.7/site-packages/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '0.16.0.dev0+8268dca' instead of '0.16.0.dev+8268dca'.
      self.metadata.version,
    
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/source/generated'
    no previously-included directories found matching '*/__pycache__'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.bak' found anywhere in distribution
    warning: no previously-included files matching '*.swp' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/local/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/local/lib/python2.7/site-packages/pip/req.py", line 330, in run_egg_info
    "%(Name)s==%(Version)s" % self.pkg_info())
  File "/mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2793, in parse
    reqs = list(parse_requirements(s))
  File "/mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/mnt/data/pauli/prj/scipy/scipy-bench/env/b35678fc20e92d459a63ed5094f8dbc9/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", u'scipy==0.16.0.dev0+8268dca', 'at', u'+8268dca')

Storing debug log for failure in /home/pauli/.pip/pip.log
```
Of course, Scipy should fix the version string format, but we cannot fix it retroactively in the past versions (which we still want to benchmark), so as it stands not pinning the setuptools version in asv currently causes problems.

**Comment by pv** [comment]
Seems to go away after `pip install --upgrade pip`, apparently was fixed recently https://github.com/pypa/pip/issues/2226

**Comment by mdboom** [comment]
Ok.  Maybe we should provide a config value to pin the version of setuptools used, otherwise use the latest?

**Comment by pv** [comment]
Some options:

1. Not upgrading setuptools at all
2. Upgrading also pip at the same time
3. Enabling pinning of setuptools via the config `matrix` option
4. Allowing some syntax in the `matrix` option to trigger `pip --upgrade`

The combination 1&3 would seem best to me --- the reason why setuptools is upgraded is not so clear to me. It would seem best to just assume the user has a working version of of virtualenv installed that will generate environments where pip works. If setuptools needs upgrading, the user can pin it to another version with the `matrix` config option?

**Comment by mdboom** [comment]
I think 1 is the simplest.  IIRC it's an historical artifact given an incompatibility between setuptools and virtualenv around 1.10 of setuptools (so asv couldn't even install into the virtualenv in the first place).  But I think we're far enough along now that we should just not upgrade it, and the user can pin it to a specific version using the matrix if necessary.
