### ISSUE TITLE
asv failing with OSError

### ISSUE THREAD

**Issue by jreback** [spacetelescope/asv#303]
just merged ``asv`` support into pandas: https://github.com/pydata/pandas/pull/9715
doing the back-benchmarks, and running into an odd issue. This is does reproduces (I initially tried on 0.1.1, now on latest master of asv)

```
[ 34.82%] ··· Running groupby.groupby_transform_multi_key4.time_groupby_transform_multi_key4Traceback (most recent call last):
  File "/Users/jreback/anaconda/bin/asv", line 9, in <module>
    load_entry_point('asv==0.2.dev762-b661eaef', 'console_scripts', 'asv')()
  File "/Users/jreback/anaconda/lib/python2.7/site-packages/asv-0.2.dev762_b661eaef-py2.7.egg/asv/main.py", line 36, in main
    result = args.func(args)
  File "/Users/jreback/anaconda/lib/python2.7/site-packages/asv-0.2.dev762_b661eaef-py2.7.egg/asv/commands/__init__.py", line 47, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/Users/jreback/anaconda/lib/python2.7/site-packages/asv-0.2.dev762_b661eaef-py2.7.egg/asv/commands/run.py", line 122, in run_from_conf_args
    skip_existing_commits=args.skip_existing_commits
  File "/Users/jreback/anaconda/lib/python2.7/site-packages/asv-0.2.dev762_b661eaef-py2.7.egg/asv/commands/run.py", line 275, in run
    profile=profile, skip=skipped_benchmarks)
  File "/Users/jreback/anaconda/lib/python2.7/site-packages/asv-0.2.dev762_b661eaef-py2.7.egg/asv/benchmarks.py", line 529, in run_benchmarks
    cwd=tmpdir)
  File "/Users/jreback/anaconda/lib/python2.7/site-packages/asv-0.2.dev762_b661eaef-py2.7.egg/asv/benchmarks.py", line 108, in run_benchmark
    cwd=cwd)
  File "/Users/jreback/anaconda/lib/python2.7/site-packages/asv-0.2.dev762_b661eaef-py2.7.egg/asv/benchmarks.py", line 236, in _run_benchmark_single
    valid_return_codes=None, cwd=cwd)
  File "/Users/jreback/anaconda/lib/python2.7/site-packages/asv-0.2.dev762_b661eaef-py2.7.egg/asv/plugins/conda.py", line 125, in run
    return self.run_executable('python', args, **kwargs)
  File "/Users/jreback/anaconda/lib/python2.7/site-packages/asv-0.2.dev762_b661eaef-py2.7.egg/asv/environment.py", line 394, in run_executable
    return util.check_output([exe] + args, **kwargs)
  File "/Users/jreback/anaconda/lib/python2.7/site-packages/asv-0.2.dev762_b661eaef-py2.7.egg/asv/util.py", line 442, in check_output
    os.killpg(proc.pid, signal.SIGTERM)
OSError: [Errno 1] Operation not permitted
```

run with [config here](https://github.com/pydata/pandas/blob/master/asv_bench/asv.conf.json)
```
asv run v0.11.0..v0.15.0 --steps 10 --skip-existing-commits
```
benches are [here](https://github.com/pydata/pandas/blob/master/asv_bench/benchmarks/groupby.py)

Note that this succeeds on other commits, just happens to fail here.

**Comment by pv** [comment]
Might be this issue:
.
https://stackoverflow.com/questions/12521705/why-would-killpg-return-not-permitted-when-ownership-is-correct
.
Killing zombie process groups succeeds on Linux but fails on OSX. The
correct fix is probably to just catch that OSError.

**Comment by pv** [comment]
Does this fix it?
.
https://github.com/pv/asv/commit/c72c94eb793d8ee15a06be2dfd06a960f338ef90

**Comment by pv** [comment]
Or, better, this: https://github.com/spacetelescope/asv/compare/master...pv:killpg-eperm-fix

**Comment by jreback** [comment]
I picked your commit....testing......(takes a while to get to the fail point) :)

**Comment by jreback** [comment]
but so far so good

**Comment by jreback** [comment]
looks like it is working! thanks!
