### ISSUE TITLE
`asv` command fails on Windows python >= 3.3 with missing `os.pathconf`

### ISSUE THREAD

**Issue by ankostis** [spacetelescope/asv#330]
After installing *asv* into python-3.4 under Windows and i try to run the `asv` command-line entry point, i get the following error:

    Traceback (most recent call last):
      File "d:\apps\winpython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\asv\util.py", line 24, in <module>
        from select import PIPE_BUF
    ImportError: cannot import name 'PIPE_BUF'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "d:\apps\winpython-64bit-3.4.3.5\python-3.4.3.amd64\lib\runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "d:\apps\winpython-64bit-3.4.3.5\python-3.4.3.amd64\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "D:\Apps\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\Scripts\asv.exe\__main__.py", line 5, in <module>
      File "d:\apps\winpython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\asv\__init__.py", line 19, in <module>
        from . import plugin_manager
      File "d:\apps\winpython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\asv\plugin_manager.py", line 10, in <module>
        from . import commands
      File "d:\apps\winpython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\asv\commands\__init__.py", line 12, in <module>
        from .. import config
      File "d:\apps\winpython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\asv\config.py", line 10, in <module>
        from . import util
      File "d:\apps\winpython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\asv\util.py", line 27, in <module>
        PIPE_BUF = os.pathconf('.', os.pathconf_names['PC_PIPE_BUF'])
    AttributeError: 'module' object has no attribute 'pathconf'

~~According to [the docs](https://docs.python.org/3.5/library/os.html#os.fpathconf), the missing attribute ``os.path.pathconf`` in python-3.3+ has been replaced by ``os.path.fpathconf``.~~

**Comment by ankostis** [comment]
Actually i totally missed the problem.
It is that the ``select.PIPE_BUF`` not undefined for *Windows*.

So probably i'm the 1st one to run *asv* under Windows.
Is it supported?

**Comment by pv** [comment]
Windows is supported in asv dev version only, currently.
