### ISSUE TITLE
console.py calling write() with bytes rather than str

### ISSUE THREAD

**Issue by seth-p** [spacetelescope/asv#334]
```
C:\Users\seth\github\pandas\asv_bench>asv continuous master HEAD
· Creating environments
· Discovering benchmarks
·· Uninstalling from py3.4-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt
·· Building for py3.4-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt
·· Installing into py3.4-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt
· Running 1320 total benchmarks (2 commits * 1 environments * 660 benchmarks)
[  0.00%] · For pandas commit hash cd9c777f:
[  0.00%] ·· Building for py3.4-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt
[  0.00%] ·· Benchmarking py3.4-Cython-matplotlib-numexpr-numpy-openpyxl-pytables-scipy-sqlalchemy-xlrd-xlwt
[  0.08%] ··· Running attrs_caching.getattr_dataframe_index.time_getattr_dataframe_index
[  0.15%] ··· Running attrs_caching.setattr_dataframe_index.time_setattr_dataframe_indexTraceback (most recent call last):
  File "C:\Python34\Scripts\asv-script.py", line 9, in <module>
    load_entry_point('asv==0.2.dev818+c07fdbf2', 'console_scripts', 'asv')()
  File "C:\Python34\lib\site-packages\asv\main.py", line 36, in main
    result = args.func(args)
  File "C:\Python34\lib\site-packages\asv\commands\__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "C:\Python34\lib\site-packages\asv\commands\continuous.py", line 49, in run_from_conf_args
    **kwargs
  File "C:\Python34\lib\site-packages\asv\commands\continuous.py", line 73, in run
    _machine_file=_machine_file)
  File "C:\Python34\lib\site-packages\asv\commands\run.py", line 276, in run
    profile=profile, skip=skipped_benchmarks)
  File "C:\Python34\lib\site-packages\asv\benchmarks.py", line 529, in run_benchmarks
    cwd=tmpdir)
  File "C:\Python34\lib\site-packages\asv\benchmarks.py", line 171, in run_benchmark
    log_result(display)
  File "C:\Python34\lib\site-packages\asv\benchmarks.py", line 91, in log_result
    log.add(" {0}{1}".format(padding, msg))
  File "C:\Python34\lib\site-packages\asv\console.py", line 355, in add
    _write_with_fallback(msg, sys.stdout.write, sys.stdout)
  File "C:\Python34\lib\site-packages\asv\console.py", line 157, in _write_with_fallback
    write(s)
  File "C:\Python34\lib\codecs.py", line 374, in write
    self.stream.write(data)
TypeError: must be str, not bytes
```

**Comment by pv** [comment]
Yes, the code there is wrong for Python 3.

gh-336 should fix it

**Comment by seth-p** [comment]
Yes, that fixed it. Thanks.
