### ISSUE TITLE
Running NumPy benchmarks using `conda`

### ISSUE THREAD

**Issue by jakirkham** [spacetelescope/asv#367]
When trying to run the benchmarks with `conda`, I run into the following error. If I run the command it lists on the command line, everything works fine. So, not sure what is wrong here. Once I create the environment and rerun the NumPy benchmarks after running this command everything works fine.

    ·· Error running /zopt/conda/envs/nanshenv/bin/conda create --yes -p /Users/kirkhamj/Developer/PyCharmCE/numpy/benchmarks/env/a598fbe7099730af760780128fdfe4f2 --use-index-cache python=2.7 pip
                 STDOUT -------->
                 Fetching package metadata: ........
                 STDERR -------->
                 Error: No packages found in current osx-64 channels matching: python 2.7*
                 
                 You can search for this package on anaconda.org with
                 
                     anaconda search -t conda python 2.7*
                 
                 You may need to install the anaconda-client command line client with
                 
                     conda install anaconda-client
    
    ·· Failure creating environment for py2.7-sixTraceback (most recent call last):
      File "/zopt/conda/envs/nanshenv/bin/asv", line 11, in <module>
        sys.exit(main())
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/main.py", line 36, in main
        result = args.func(args)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/commands/__init__.py", line 47, in run_from_args
        return cls.run_from_conf_args(conf, args)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/commands/continuous.py", line 50, in run_from_conf_args
        show_stderr=args.show_stderr, bench=args.bench, machine=args.machine
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/commands/continuous.py", line 74, in run
        _machine_file=_machine_file)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/commands/run.py", line 186, in run
        environments = Setup.run(conf=conf, parallel=parallel)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/commands/setup.py", line 72, in run
        list(map(_create, environments))
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/commands/setup.py", line 20, in _create
        env.create()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/environment.py", line 278, in create
        self._setup()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/plugins/conda.py", line 102, in _setup
        'pip'])
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/util.py", line 262, in check_call
        cwd=cwd)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/asv/util.py", line 431, in check_output
        raise ProcessError(args, retcode, stdout, stderr)
    asv.util.ProcessError: Command '/zopt/conda/envs/nanshenv/bin/conda create --yes -p /Users/kirkhamj/Developer/PyCharmCE/numpy/benchmarks/env/a598fbe7099730af760780128fdfe4f2 --use-index-cache python=2.7 pip' returned non-zero exit status 1

**Comment by jakirkham** [comment]
Nevermind, apparently really messed up the working copy of numpy using virtualenv from before. Cleaning out the cruft resolved this.
