### ISSUE TITLE
ASVs import method seems to create invalid import rings

### ISSUE THREAD

**Issue by seberg** [spacetelescope/asv#369]
I am not sure this is an ASV bug or can be avoided, but adding `import numpy.distutils.cpuinfo` to `numpy/testing/nosetester.py` broke the automatic tests as below, it seems that for some reason the wrong commands is imported (not global but ASV) upon doing that import.

Anyway, I will just move the warnings stuff elsewhere and be done with it, just to note.

```
+python /home/travis/build/numpy/numpy/builds/venv/bin/asv dev
· Discovering benchmarks
·· Error running /home/travis/build/numpy/numpy/builds/venv/bin/python /home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/benchmark.py discover benchmarks /tmp/tmpGBvoqo
             STDOUT -------->
             
             STDERR -------->
             Traceback (most recent call last):
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/benchmark.py", line 658, in <module>
                 list_benchmarks(benchmark_dir, fp)
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/benchmark.py", line 639, in list_benchmarks
                 for benchmark in disc_benchmarks(root):
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/benchmark.py", line 624, in disc_benchmarks
                 for module in disc_files(root, os.path.basename(root) + '.'):
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/benchmark.py", line 613, in disc_files
                 module = import_module(package + filename)
               File "/opt/python/2.7.9/lib/python2.7/importlib/__init__.py", line 37, in import_module
                 __import__(name)
               File "benchmarks/__init__.py", line 3, in <module>
                 from . import common
               File "benchmarks/common.py", line 3, in <module>
                 import numpy
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
                 from . import add_newdocs
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
                 from numpy.lib import add_newdoc
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
                 from .type_check import *
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
                 import numpy.core.numeric as _nx
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/numpy/core/__init__.py", line 58, in <module>
                 from numpy.testing.nosetester import _numpy_tester
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/numpy/testing/__init__.py", line 13, in <module>
                 from .nosetester import run_module_suite, NoseTester as Tester
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/numpy/testing/nosetester.py", line 14, in <module>
                 import numpy.distutils.cpuinfo
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/numpy/distutils/cpuinfo.py", line 25, in <module>
                 from commands import getstatusoutput
               File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/commands/__init__.py", line 12, in <module>
                 from .. import config
             ValueError: Attempted relative import beyond toplevel package
Traceback (most recent call last):
  File "/home/travis/build/numpy/numpy/builds/venv/bin/asv", line 9, in <module>
    load_entry_point('asv==0.1.1', 'console_scripts', 'asv')()
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/main.py", line 36, in main
    result = args.func(args)
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/commands/__init__.py", line 47, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/commands/dev.py", line 31, in run_from_conf_args
    return cls.run(conf, bench=args.bench, machine=args.machine, python=args.python)
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/commands/dev.py", line 37, in run
    _machine_file=_machine_file)
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/commands/run.py", line 197, in run
    benchmarks = Benchmarks(conf, regex=bench)
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/benchmarks.py", line 285, in __init__
    for benchmark in benchmarks:
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/benchmarks.py", line 325, in disc_benchmarks
    dots=False)
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/environment.py", line 429, in run
    self._executable] + args, **kwargs)
  File "/home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/util.py", line 431, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/home/travis/build/numpy/numpy/builds/venv/bin/python /home/travis/build/numpy/numpy/builds/venv/lib/python2.7/site-packages/asv/benchmark.py discover benchmarks /tmp/tmpGBvoqo' returned non-zero exit status 1
```

**Comment by pv** [comment]
asv version?
there used to be a bug like this, but it should be fixed in master

**Comment by pv** [comment]
dup of gh-275 probably

**Comment by seberg** [comment]
Sorry, yes I am sure it is. Was lazy and did not search the lsit :(. numpy seems to also use 0.1.1.

**Comment by pv** [comment]
probably travis-ci should be told to use the current master (best to hardcode commit to avoid asv master bugs resulting to failures)
