### ISSUE TITLE
Feature request: better support for Windows

### ISSUE THREAD

**Issue by rs2** [spacetelescope/asv#408]
I had to patch the code heavily to make asv work well on Windows (for pandas). Let's join the efforts.

**Comment by pv** [comment]
You should also say what exactly you changed, in order for this to be constructive.
As far as I know, everything works fine on Windows, but I'm not using asv on Windows daily.

**Comment by pv** [comment]
Aside from gh-409 it worked out of the box for me for pandas.
Reopen if you have further specific suggestion.

**Comment by rs2** [comment]
Guys, let's reopen this one, and let me submit a pull request. The handling of pipes on Windows is not watertight.

```cmd
D:\@workspace\pandas\asv_bench>python --version
Python 3.5.1 :: Anaconda 2.5.0 (64-bit)

D:\@workspace\pandas\asv_bench>pip freeze|grep asv
asv==0.1.1

D:\@workspace\pandas\asv_bench>asv dev -b groupby
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\asv\util.py", line 24, in <module>
    from select import PIPE_BUF
ImportError: cannot import name 'PIPE_BUF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\asv.exe\__main__.py", line 5, in <module>
  File "c:\anaconda3\lib\site-packages\asv\__init__.py", line 19, in <module>
    from . import plugin_manager
  File "c:\anaconda3\lib\site-packages\asv\plugin_manager.py", line 10, in <module>
    from . import commands
  File "c:\anaconda3\lib\site-packages\asv\commands\__init__.py", line 12, in <module>
    from .. import config
  File "c:\anaconda3\lib\site-packages\asv\config.py", line 10, in <module>
    from . import util
  File "c:\anaconda3\lib\site-packages\asv\util.py", line 27, in <module>
    PIPE_BUF = os.pathconf('.', os.pathconf_names['PC_PIPE_BUF'])
AttributeError: module 'os' has no attribute 'pathconf'
```

**Comment by pv** [comment]
asv 0.1.1 does not support Windows, but the git master version does.

**Comment by rs2** [comment]
Let me try that.
