### ISSUE TITLE
BUG: KeyError: started_at if build fails for a commit

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/asv#433]
If the build step fails, this causes a KeyError once all the tests have been skipped:

```
[  0.21%] · For photutils commit hash c449e2a4:
[  0.21%] ·· Building for conda-py2.7-Cython-astropy1.1-numpy1.11
[  0.21%] ··· Error running /home/robitaille/benchmarks/photutils-benchmarks/env/e3fd1b7a2a75a5f94418883e6c98107a/bin/python setup.py build
              STDOUT -------->
              
              STDERR -------->
              Traceback (most recent call last):
                File "setup.py", line 19, in <module>
                  from astropy.setup_helpers import (register_commands, adjust_compiler,
              ImportError: No module named setup_helpers

[  0.21%] ·· Skipping conda-py2.7-Cython-astropy1.1-numpy1.11
[  0.21%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_sm_ap_err_subpixel_05 skipped
[  0.21%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_sm_ap_err_subpixel_01 skipped
[  0.21%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_sm_ap_err_exact skipped
[  0.22%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_bg_ap_exact skipped
[  0.22%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_sm_ap_exact skipped
[  0.22%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_bg_ap_exact skipped
[  0.22%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_bg_ap_err_subpixel_01 skipped
[  0.22%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_bg_ap_subpixel_01 skipped
[  0.23%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_bg_ap_err_subpixel_05 skipped
[  0.23%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_bg_ap_subpixel_05 skipped
[  0.23%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_bg_ap_err_exact skipped
[  0.23%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_bg_ap_err_subpixel_05 skipped
[  0.23%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_bg_ap_err_subpixel_01 skipped
[  0.24%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_sm_ap_err_exact skipped
[  0.24%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_bg_ap_subpixel_01 skipped
[  0.24%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_bg_ap_subpixel_05 skipped
[  0.24%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_bg_ap_err_exact skipped
[  0.24%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_bg_ap_err_exact skipped
[  0.25%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_bg_ap_subpixel_05 skipped
[  0.25%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_bg_ap_subpixel_01 skipped
[  0.25%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_sm_ap_err_exact skipped
[  0.25%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_bg_ap_subpixel_05 skipped
[  0.25%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_bg_ap_subpixel_01 skipped
[  0.26%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_bg_ap_subpixel_01 skipped
[  0.26%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_bg_ap_subpixel_05 skipped
[  0.26%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_sm_ap_exact skipped
[  0.26%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_sm_ap_subpixel_01 skipped
[  0.26%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_bg_ap_err_exact skipped
[  0.26%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_sm_ap_exact skipped
[  0.27%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_sm_ap_subpixel_05 skipped
[  0.27%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_sm_ap_exact skipped
[  0.27%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_sm_ap_subpixel_05 skipped
[  0.27%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_sm_ap_subpixel_01 skipped
[  0.27%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_sm_ap_err_exact skipped
[  0.28%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_sm_ap_err_subpixel_05 skipped
[  0.28%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_sm_ap_err_subpixel_01 skipped
[  0.28%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_sm_ap_err_subpixel_05 skipped
[  0.28%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_bg_ap_exact skipped
[  0.28%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_sm_ap_err_subpixel_05 skipped
[  0.29%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_sm_ap_err_subpixel_01 skipped
[  0.29%] ··· Benchmark geometry.time_circular_small_exact skipped
[  0.29%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_bg_ap_subpixel_01 skipped
[  0.29%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_sm_ap_err_subpixel_01 skipped
[  0.29%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_bg_ap_subpixel_05 skipped
[  0.30%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_sm_ap_err_subpixel_01 skipped
[  0.30%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_sm_ap_err_exact skipped
[  0.30%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_bg_ap_err_subpixel_05 skipped
[  0.30%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_bg_ap_err_subpixel_01 skipped
[  0.30%] ··· Benchmark geometry.time_elliptical_small_subpixel_5 skipped
[  0.31%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_bg_ap_err_exact skipped
[  0.31%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_bg_ap_err_subpixel_01 skipped
[  0.31%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_bg_ap_err_subpixel_05 skipped
[  0.31%] ··· Benchmark geometry.time_elliptical_small_subpixel_1 skipped
[  0.31%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_sm_ap_err_subpixel_05 skipped
[  0.32%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_bg_ap_exact skipped
[  0.32%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_sm_ap_subpixel_01 skipped
[  0.32%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_sm_ap_subpixel_05 skipped
[  0.32%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_sm_ap_exact skipped
[  0.32%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_bg_ap_exact skipped
[  0.32%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_bg_ap_err_exact skipped
[  0.33%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_sm_ap_err_subpixel_01 skipped
[  0.33%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_bg_ap_subpixel_05 skipped
[  0.33%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_sm_ap_err_subpixel_05 skipped
[  0.33%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_bg_ap_err_exact skipped
[  0.33%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_bg_ap_subpixel_01 skipped
[  0.34%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_sm_ap_subpixel_01 skipped
[  0.34%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_sm_ap_subpixel_05 skipped
[  0.34%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_bg_ap_err_exact skipped
[  0.34%] ··· Benchmark geometry.time_circular_big_exact skipped
[  0.34%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_sm_ap_err_subpixel_01 skipped
[  0.35%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_bg_ap_err_subpixel_05 skipped
[  0.35%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_sm_ap_exact skipped
[  0.35%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_sm_ap_err_subpixel_05 skipped
[  0.35%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_bg_ap_err_subpixel_01 skipped
[  0.35%] ··· Benchmark geometry.time_elliptical_big_subpixel_5 skipped
[  0.36%] ··· Benchmark geometry.time_elliptical_big_subpixel_1 skipped
[  0.36%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_bg_ap_exact skipped
[  0.36%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_sm_ap_subpixel_05 skipped
[  0.36%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_sm_ap_subpixel_01 skipped
[  0.36%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_bg_ap_err_subpixel_05 skipped
[  0.37%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_bg_ap_err_subpixel_01 skipped
[  0.37%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_bg_ap_exact skipped
[  0.37%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_sm_ap_exact skipped
[  0.37%] ··· Benchmark geometry.time_circular_small_subpixel_1 skipped
[  0.37%] ··· Benchmark geometry.time_circular_small_subpixel_5 skipped
[  0.38%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_sm_ap_err_subpixel_01 skipped
[  0.38%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_sm_ap_err_subpixel_05 skipped
[  0.38%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_mult_sm_ap_exact skipped
[  0.38%] ··· Benchmark geometry.time_circular_big_subpixel_1 skipped
[  0.38%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_sm_ap_subpixel_05 skipped
[  0.38%] ··· Benchmark geometry.time_circular_big_subpixel_5 skipped
[  0.39%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_bg_ap_exact skipped
[  0.39%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_sing_sm_ap_subpixel_01 skipped
[  0.39%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_sm_ap_subpixel_01 skipped
[  0.39%] ··· Benchmark aperture.EllipticalAperturePhotometry.time_sing_sm_ap_subpixel_05 skipped
[  0.39%] ··· Benchmark geometry.time_elliptical_small_exact skipped
[  0.40%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_sing_sm_ap_err_exact skipped
[  0.40%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_bg_ap_subpixel_05 skipped
[  0.40%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_bg_ap_subpixel_01 skipped
[  0.40%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_sm_ap_subpixel_05 skipped
[  0.40%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_sm_ap_subpixel_01 skipped
[  0.41%] ··· Benchmark aperture.CircularAnnulusPhotometry.time_mult_sm_ap_err_exact skipped
[  0.41%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_bg_ap_err_subpixel_01 skipped
[  0.41%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_bg_ap_err_subpixel_01 skipped
[  0.41%] ··· Benchmark aperture.CircularAperturePhotometry.time_sing_bg_ap_err_subpixel_05 skipped
[  0.41%] ··· Benchmark aperture.EllipticalAnnulusPhotometry.time_mult_bg_ap_err_subpixel_05 skipped
[  0.42%] ··· Benchmark geometry.time_elliptical_big_exact skipped
[  0.42%] ··· Benchmark aperture.CircularAperturePhotometry.time_mult_sm_ap_err_exact skippedTraceback (most recent call last):
  File "/disk1/data/anaconda/envs/asv/bin/asv", line 9, in <module>
    load_entry_point('asv===0.2.dev0-', 'console_scripts', 'asv')()
  File "/disk1/data/anaconda/envs/asv/lib/python2.7/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/disk1/data/anaconda/envs/asv/lib/python2.7/site-packages/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/disk1/data/anaconda/envs/asv/lib/python2.7/site-packages/asv/commands/run.py", line 123, in run_from_conf_args
    **kwargs
  File "/disk1/data/anaconda/envs/asv/lib/python2.7/site-packages/asv/commands/run.py", line 278, in run
    d['started_at'], d['ended_at'])
KeyError: u'started_at'
```

**Comment by pv** [comment]
Fix in #434
