### ISSUE TITLE
gh-pages blows if some previously benchmarked commit is no longer available within branches

### ISSUE THREAD

**Issue by yarikoptic** [spacetelescope/asv#514]
```shell
(git)hopa:~datalad/datalad[enh-bench-api]git
$> asv gh-pages
[ 11.11%] · Loading machine info
[ 22.22%] · Getting params, commits, tags and branches
[ 33.33%] · Loading results.
[ 44.44%] · Detecting steps
[ 55.56%] · Generating graphs.
[ 66.67%] · Generating output for SummaryGrid
[ 77.78%] · Generating output for SummaryList
[ 88.89%] · Generating output for RegressionsTraceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/bin/asv", line 11, in <module>
    sys.exit(main())
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/plugins/github.py", line 36, in run_from_conf_args
    return cls.run(conf=conf, no_push=args.no_push)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/plugins/github.py", line 43, in run
    Publish.run(conf)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/commands/publish.py", line 193, in run
    cls.publish(conf, repo, benchmarks, graphs, revisions)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/plugins/regressions.py", line 61, in publish
    cls._save_feed(conf, benchmarks, regressions, revisions, revision_to_hash)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/plugins/regressions.py", line 124, in _save_feed
    revision = revisions[results.commit_hash]
KeyError: u'cb2c0f670d863669e502feb6b6f91865e7c38d8a'
```
the commit is there though:
```shell
$> git show cb2c0f670d863669e502feb6b6f91865e7c38d8a
commit cb2c0f670d863669e502feb6b6f91865e7c38d8a
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Mon Jan 16 15:28:57 2017 -0500
...
```
but probably not reachable within any branch...  quick workaround was to make a dummy branch of that commit and then asv proceeded.

**Comment by pv** [comment]
this one should be now fixed
