### ISSUE TITLE
Build Errors with cython

### ISSUE THREAD

**Issue by jbrockmendel** [spacetelescope/asv#542]
Over in pandas I'm being told to "get asv to work it should be quite straightforward" on a commit that adds a new new pyx file `tslibs.timezones`.  When I run `asv continuous -f 1.1 -E virtualenv HEAD -b timeseries.py` I get the following error:

```
asv continuous -f 1.1 -E virtualenv HEAD -b timeseries.py
· Creating environments
· Discovering benchmarks
·· Uninstalling from virtualenv-py2.7-Cython-matplotlib-numexpr-numpy-openpyxl-pytest-scipy-sqlalchemy-tables-xlrd-xlsxwriter-xlwt
·· Installing into virtualenv-py2.7-Cython-matplotlib-numexpr-numpy-openpyxl-pytest-scipy-sqlalchemy-tables-xlrd-xlsxwriter-xlwt..
·· Error running ~/pd/tslibs-timezones/pandas/asv_bench/env/dbb8113eac34359a9ef26b93e54a1d03/bin/python ~/.local/lib/python2.7/site-packages/asv/benchmark.py discover ~/pd/tslibs-timezones/pandas/asv_bench/benchmarks /tmp/tmpUDGky2
             STDOUT -------->
             
             STDERR -------->
             Traceback (most recent call last):
               File "~/.local/lib/python2.7/site-packages/asv/benchmark.py", line 867, in <module>
                 commands[mode](args)
               File "~/.local/lib/python2.7/site-packages/asv/benchmark.py", line 812, in main_discover
                 list_benchmarks(benchmark_dir, fp)
               File "~/.local/lib/python2.7/site-packages/asv/benchmark.py", line 797, in list_benchmarks
                 for benchmark in disc_benchmarks(root):
               File "~/.local/lib/python2.7/site-packages/asv/benchmark.py", line 696, in disc_benchmarks
                 for module in disc_files(root, os.path.basename(root) + '.'):
               File "~/.local/lib/python2.7/site-packages/asv/benchmark.py", line 648, in disc_files
                 module = import_module(package + filename)
               File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
                 __import__(name)
               File "~/pd/tslibs-timezones/pandas/asv_bench/benchmarks/index_object.py", line 1, in <module>
                 from .pandas_vb_common import *
               File "~/pd/tslibs-timezones/pandas/asv_bench/benchmarks/pandas_vb_common.py", line 1, in <module>
                 from pandas import *
               File "~/pd/tslibs-timezones/pandas/asv_bench/env/dbb8113eac34359a9ef26b93e54a1d03/local/lib/python2.7/site-packages/pandas/__init__.py", line 35, in <module>
                 "the C extensions first.".format(module))
             ImportError: C extension: No module named tslibs.timezones not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```
This is roughly the error that I would get if I tried to import `pandas` in the interpreter without having first run `setup.py build_ext --inplace`.  Is it conceivable that `asv continuous` is somehow skipping that step?  Or running it but with an earlier version of `setup.py` that doesn't know about tslibs/timezones.pyx?

Where it gets even weirder is that I can replace the command with `asv continuous -f 1.1 -E virtualenv master -b timeseries.py` and get essentially the same error.  But on the "master" branch, it shouldn't be trying to import `tslibs.timezones` at all.

Any thoughts on what could be going on?  Smart money is on me having screwed up somewhere along the line.

**Comment by jbrockmendel** [comment]
It tentatively looks like moving `timezones` from pandas/_libs/tslibs/timezones.pyx to pandas/_libs/timezones.pyx gets rid of this error.  Hopefully someone finds that information useful.

**Comment by pv** [comment]
You can try removing `asv_bench/env/` and trying again, to clear up the wheel caches etc.

Aside from that, the problem is that a non-working build of pandas was produced --- the reason for that is pandas-specific, no idea how that would occur.
